version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: evalua-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evalua
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./
    container_name: evalua-backend
    restart: always
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      DB_HOST: evalua-postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: evalua
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:
